version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

#BeforeInstall, AfterInstall(codeDeploy 수명주기)에 실행될 파일 지정
hooks:
  BeforeInstall:
    - location: scripts/before-deploy.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/{{github.ref}}.sh
      timeout: 200
      runas: ubuntu
