version: '3.7'

services:
  pog_server:
    container_name: pog_server
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile.dev
      labels:
        - pog_server
    env_file:
      - .env
    ports:
      - 3000:3000
    working_dir: /app/pog_server

